# Generated by Django 3.2.19 on 2023-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_current_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_jobs',
            name='date_posted',
            field=models.CharField(max_length=50),
        ),
    ]
