# Generated by Django 3.2.19 on 2023-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_current_jobs_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_jobs',
            name='user_id',
            field=models.IntegerField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
