# Generated by Django 3.2.19 on 2023-07-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_current_jobs_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_jobs',
            name='user_id',
        ),
    ]
